version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $ENV
      - echo $env
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo `pwd`
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - cd docker
      - make build
      - docker images
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - make push
      - printf '[{"name":"port-nginx","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/port-nginx:latest > imagedefinitions.json

artifacts:
  files:
    - docker/imagedefinitions.json
    - aws/taskdef.json
    - aws/appspec.yaml